### PR TITLE
xdot event leak fix

### PR DESCRIPTION
**Pull request by ache7**
Discussed here - https://software.intel.com/en-us/forums/opencl/topic/701907

### CODE REVIEW

**Comment by hughperkins** [comment]
Cool.  Kind of want a unit test.  Could be to just call the blas over and over again, from a torch lua script . But something I can run to check the behavior before/after the patch. Ideally without having to install an entire other project :-)

**Comment by guoyejun** [comment]
@ache7  i'm looks at the perf issue that you reported from beignet perspective, could you let me know the full command line to reproduce it? thanks.

i tried the following command (just copy from https://github.com/jcjohnson/neural-style) with LLVM3.9+latest beignet, and looks that it is not bad.
th neural_style.lua -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -output_image profile.png -model_file models/nin_imagenet_conv.caffemodel -proto_file models/train_val.prototxt -gpu 0 -backend clnn -num_iterations 1000 -seed 123 -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 1000 -image_size 512 -optimizer adam

welcome to talk more (i've made my email public, feel free to contact me in what ever method that you like).

@hughperkins  sorry to use this thread to talk something others, i just could not find a direct way to talk to ache7, :(

**Comment by ache7** [comment]
@guoyejun any command line will reproduce event leak, beignet will not return "out of memory" errors, small amounts of memory will leak with every call to xdot. But intel opencl drivers count every unreleased event and refuse to create more events at some point.

**Comment by guoyejun** [comment]
@ache7 i'm looks at the performance issue (not the event issue) from beignet perspective. beignet is the open source intel opencl driver. I tried with latest beignet code, and looks that it is not bad. Just want to see if i did something wrong since the result is big different with what you reported. thanks.

**Comment by ache7** [comment]
Fixed with other functions with event leaks in https://github.com/clMathLibraries/clBLAS/pull/300/commits/03254e597e6649116a8bc249d8a45f973b7e32cf

**Pull request closed without merging**
